### ISSUE TITLE
[Qt5.5] Build error

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#1790]
Is there any library are missing on my system, which cause the following error?:
```
../../../src/lib/webengine/webpage.cpp: In member function 'QVariant WebPage::execJavaScript(const QString&, int)':
../../../src/lib/webengine/webpage.cpp:113:56: error: no matching function for call to 'QTimer::singleShot(int&, QPointer<QEventLoop>&, void (QEventLoop::*)())'
     QTimer::singleShot(timeout, loop, &QEventLoop::quit);
                                                        ^
../../../src/lib/webengine/webpage.cpp:113:56: note: candidates are:
In file included from /opt/qt5/include/qt5/QtCore/QTimer:1:0,
                 from ../../../src/lib/tools/toolbutton.h:22,
                 from ../../../src/lib/tabwidget/tabwidget.h:26,
                 from ../../../src/lib/webengine/webpage.cpp:40:
/opt/qt5/include/qt5/QtCore/qtimer.h:73:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/opt/qt5/include/qt5/QtCore/qtimer.h:73:17: note:   no known conversion for argument 3 from 'void (QEventLoop::*)()' to 'const char*'
/opt/qt5/include/qt5/QtCore/qtimer.h:74:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/opt/qt5/include/qt5/QtCore/qtimer.h:74:17: note:   candidate expects 4 arguments, 3 provided
/opt/qt5/include/qt5/QtCore/qtimer.h:86:24: note: template<class Func1> static void QTimer::singleShot(int, const typename QtPrivate::FunctionPointer<Func>::Object*, Func1)
     static inline void singleShot(int msec, const typename QtPrivate::FunctionPointer<Func1>::Object *receiver, Func1 slot)
                        ^
/opt/qt5/include/qt5/QtCore/qtimer.h:86:24: note:   template argument deduction/substitution failed:
../../../src/lib/webengine/webpage.cpp:113:56: note:   mismatched types 'const typename QtPrivate::FunctionPointer<Func>::Object*' and 'QPointer<QEventLoop>'
     QTimer::singleShot(timeout, loop, &QEventLoop::quit);
                                                        ^
In file included from /opt/qt5/include/qt5/QtCore/QTimer:1:0,
                 from ../../../src/lib/tools/toolbutton.h:22,
                 from ../../../src/lib/tabwidget/tabwidget.h:26,
                 from ../../../src/lib/webengine/webpage.cpp:40:
/opt/qt5/include/qt5/QtCore/qtimer.h:91:24: note: template<class Func1> static void QTimer::singleShot(int, Qt::TimerType, const typename QtPrivate::FunctionPointer<Func>::Object*, Func1)
     static inline void singleShot(int msec, Qt::TimerType timerType, const typename QtPrivate::FunctionPointer<Func1>::Object *receiver,
                        ^
/opt/qt5/include/qt5/QtCore/qtimer.h:91:24: note:   template argument deduction/substitution failed:
../../../src/lib/webengine/webpage.cpp:113:56: note:   cannot convert 'loop' (type 'QPointer<QEventLoop>') to type 'Qt::TimerType'
     QTimer::singleShot(timeout, loop, &QEventLoop::quit);
                                                        ^
In file included from /opt/qt5/include/qt5/QtCore/QTimer:1:0,
                 from ../../../src/lib/tools/toolbutton.h:22,
                 from ../../../src/lib/tabwidget/tabwidget.h:26,
                 from ../../../src/lib/webengine/webpage.cpp:40:
/opt/qt5/include/qt5/QtCore/qtimer.h:105:24: note: template<class Func1> static void QTimer::singleShot(int, Func1)
     static inline void singleShot(int msec, Func1 slot)
                        ^
/opt/qt5/include/qt5/QtCore/qtimer.h:105:24: note:   template argument deduction/substitution failed:
../../../src/lib/webengine/webpage.cpp:113:56: note:   candidate expects 2 arguments, 3 provided
     QTimer::singleShot(timeout, loop, &QEventLoop::quit);
                                                        ^
In file included from /opt/qt5/include/qt5/QtCore/QTimer:1:0,
                 from ../../../src/lib/tools/toolbutton.h:22,
                 from ../../../src/lib/tabwidget/tabwidget.h:26,
                 from ../../../src/lib/webengine/webpage.cpp:40:
/opt/qt5/include/qt5/QtCore/qtimer.h:110:24: note: template<class Func1> static void QTimer::singleShot(int, Qt::TimerType, Func1)
     static inline void singleShot(int msec, Qt::TimerType timerType, Func1 slot)
                        ^
/opt/qt5/include/qt5/QtCore/qtimer.h:110:24: note:   template argument deduction/substitution failed:
../../../src/lib/webengine/webpage.cpp:113:56: note:   cannot convert 'loop' (type 'QPointer<QEventLoop>') to type 'Qt::TimerType'
     QTimer::singleShot(timeout, loop, &QEventLoop::quit);
                                                        ^
In file included from /opt/qt5/include/qt5/QtCore/QTimer:1:0,
                 from ../../../src/lib/tools/toolbutton.h:22,
                 from ../../../src/lib/tabwidget/tabwidget.h:26,
                 from ../../../src/lib/webengine/webpage.cpp:40:
/opt/qt5/include/qt5/QtCore/qtimer.h:118:13: note: template<class Func1> static typename QtPrivate::QEnableIf<((! QtPrivate::FunctionPointer<Func>::IsPointerToMemberFunction) && (! QtPrivate::is_same<const char*, Func1>::value)), void>::Type QTimer::singleShot(int, QObject*, Func1)
             singleShot(int msec, QObject *context, Func1 slot)
             ^
/opt/qt5/include/qt5/QtCore/qtimer.h:118:13: note:   template argument deduction/substitution failed:
/opt/qt5/include/qt5/QtCore/qtimer.h: In substitution of 'template<class Func1> static typename QtPrivate::QEnableIf<((! QtPrivate::FunctionPointer<Func>::IsPointerToMemberFunction) && (! QtPrivate::is_same<const char*, Func1>::value)), void>::Type QTimer::singleShot(int, QObject*, Func1) [with Func1 = void (QEventLoop::*)()]':
../../../src/lib/webengine/webpage.cpp:113:56:   required from here
/opt/qt5/include/qt5/QtCore/qtimer.h:118:13: error: invalid use of incomplete type 'struct QtPrivate::QEnableIf<false, void>'
In file included from /opt/qt5/include/qt5/QtWebEngineWidgets/qtwebenginewidgetsglobal.h:40:0,
                 from /opt/qt5/include/qt5/QtWebEngineWidgets/qwebenginepage.h:40,
                 from /opt/qt5/include/qt5/QtWebEngineWidgets/QWebEnginePage:1,
                 from ../../../src/lib/webengine/webpage.h:21,
                 from ../../../src/lib/webengine/webpage.cpp:18:
/opt/qt5/include/qt5/QtCore/qglobal.h:1073:45: error: declaration of 'struct QtPrivate::QEnableIf<false, void>'
 template <bool B, typename T = void> struct QEnableIf;
                                             ^
In file included from /opt/qt5/include/qt5/QtCore/QTimer:1:0,
                 from ../../../src/lib/tools/toolbutton.h:22,
                 from ../../../src/lib/tabwidget/tabwidget.h:26,
                 from ../../../src/lib/webengine/webpage.cpp:40:
/opt/qt5/include/qt5/QtCore/qtimer.h:125:13: note: template<class Func1> static typename QtPrivate::QEnableIf<((! QtPrivate::FunctionPointer<Func>::IsPointerToMemberFunction) && (! QtPrivate::is_same<const char*, Func1>::value)), void>::Type QTimer::singleShot(int, Qt::TimerType, QObject*, Func1)
             singleShot(int msec, Qt::TimerType timerType, QObject *context, Func1 slot)
             ^
/opt/qt5/include/qt5/QtCore/qtimer.h:125:13: note:   template argument deduction/substitution failed:
../../../src/lib/webengine/webpage.cpp:113:56: note:   cannot convert 'loop' (type 'QPointer<QEventLoop>') to type 'Qt::TimerType'
     QTimer::singleShot(timeout, loop, &QEventLoop::quit);
                                                        ^
make[1]: *** [../../../build/webpage.o] Error 1
make[1]: Leaving directory `/home/az/rpmbuild/BUILD/qupzilla55-1.8.9/x86_64-redhat-linux-gnu/src/lib'
make: *** [sub-src-lib-make_first] Error 2
```

branch: **Qt5.5** 9a3e1e4

**Comment by nowrep** [comment]
And do you actually have Qt 5.5?

**Comment by cranes-bill** [comment]
Qt 5.5.1, i think.

**Comment by cranes-bill** [comment]
Do you need any more information?

**Comment by JHooverman** [comment]
@nowrep: I am just curious: Should it be possible to compile the qt5.5 branch against qt5.5-qtwebengine and qt5.5-qtwebkit?

**Comment by nowrep** [comment]
@JHooverman No, it's only for QtWebEngine 5.5.
@cranes-bill No, idea what's wrong (also no time to investigate now, sorry).

**Comment by JHooverman** [comment]
@nowrep: Could it be, that the qt-version used by @cranes-bill to compile the qt5.5 branch is too old or too fresh? I remember, that it took quite a long time, until I found a matching qt-version to compile against the master branch.

**Comment by cranes-bill** [comment]
@nowrep No problem, i just was not shure is i have 5.5 or 5.5.1, so i asked you again, just to make sure that you don't wait me to confirm that.
The version is **5.5.1**

@JHooverman I'm guessing you are right, or just i'm missing any library...

**Comment by nowrep** [comment]
No, it's not missing library. It's an issue with your compiler not finding the correct overload for `connect` function.

Do you use gcc or clang, and which version?

**Comment by cranes-bill** [comment]
**gcc 4.8.3 20140911**
Sorry for the late answer!

**Comment by cranes-bill** [comment]
OK, if i'm playing dummy as follows:
```diff
diff --git a/qupzilla/src/lib/webengine/webpage.cpp b/qupzilla.new/src/lib/webengine/webpage.cpp
index 0a43523..8adaf38 100644
--- a/qupzilla/src/lib/webengine/webpage.cpp
+++ b/qupzilla.new/src/lib/webengine/webpage.cpp
@@ -110,7 +110,7 @@ QVariant WebPage::execJavaScript(const QString &scriptSource, int timeout)
 {
     QPointer<QEventLoop> loop = new QEventLoop;
     QVariant result;
-    QTimer::singleShot(timeout, loop, &QEventLoop::quit);
+//    QTimer::singleShot(timeout, loop, &QEventLoop::quit);
 
     runJavaScript(scriptSource, [loop, &result](const QVariant &res) {
         if (loop && loop->isRunning()) {
diff --git a/qupzilla/src/lib/webengine/webview.cpp b/qupzilla.new/src/lib/webengine/webview.cpp
index 8bc01b9..ce632de 100644
--- a/qupzilla/src/lib/webengine/webview.cpp
+++ b/qupzilla.new/src/lib/webengine/webview.cpp
@@ -847,7 +847,7 @@ void WebView::checkForForm(QAction *action, const QPoint &pos)
         const QVariantMap &map = res.toMap();
         if (!act || map.isEmpty())
             return;
-
+/*
         const QUrl url = map.value(QSL("action")).toUrl();
         const QString method = map.value(QSL("method")).toString();
 
@@ -856,7 +856,7 @@ void WebView::checkForForm(QAction *action, const QPoint &pos)
             act->setIcon(QIcon(QSL(":icons/menu/search-icon.png")));
             act->setText(tr("Create Search Engine"));
             connect(act, &QAction::triggered, this, &WebView::createSearchEngine);
-        }
+        } */
     });
 }
 
```
i can compile this branch.
Now QupZilla has crashed any time on exit, probably due to this dirty hack....

**Comment by nowrep** [comment]
Why the change in webview.cpp?

**Comment by cranes-bill** [comment]
Because also has an error report there. My guess it's related to disabled function, but if not, please tell me if you need to know what is the error!
And thank you!

**Comment by nowrep** [comment]
Yes, show me the error please.

**Comment by cranes-bill** [comment]
```
../../../src/lib/webengine/webview.cpp: In lambda function:
../../../src/lib/webengine/webview.cpp:858:81: erreur: no matching function for call to ‘WebView::connect(const QPointer<QAction>&, void (QAction::*)(bool), WebView*, void (WebView::*)())’
             connect(act, &QAction::triggered, this, &WebView::createSearchEngine);
                                                                                 ^
../../../src/lib/webengine/webview.cpp:858:81: note: candidates are:
In file included from /opt/qt5/include/qt5/QtCore/qsharedpointer_impl.h:57:0,
                 from /opt/qt5/include/qt5/QtCore/qsharedpointer.h:42,
                 from /opt/qt5/include/qt5/QtGui/qpixmap.h:41,
                 from /opt/qt5/include/qt5/QtGui/qicon.h:40,
                 from /opt/qt5/include/qt5/QtGui/QIcon:1,
                 from ../../../src/lib/webengine/webview.h:21,
                 from ../../../src/lib/webengine/webview.cpp:18:
/opt/qt5/include/qt5/QtCore/qobject.h:196:36: note: static QMetaObject::Connection QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static QMetaObject::Connection connect(const QObject *sender, const char *signal,
                                    ^
/opt/qt5/include/qt5/QtCore/qobject.h:196:36: note:   no known conversion for argument 2 from ‘void (QAction::*)(bool)’ to ‘const char*’
/opt/qt5/include/qt5/QtCore/qobject.h:199:36: note: static QMetaObject::Connection QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static QMetaObject::Connection connect(const QObject *sender, const QMetaMethod &signal,
                                    ^
/opt/qt5/include/qt5/QtCore/qobject.h:199:36: note:   no known conversion for argument 2 from ‘void (QAction::*)(bool)’ to ‘const QMetaMethod&’
/opt/qt5/include/qt5/QtCore/qobject.h:475:32: note: QMetaObject::Connection QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline QMetaObject::Connection QObject::connect(const QObject *asender, const char *asignal,
                                ^
/opt/qt5/include/qt5/QtCore/qobject.h:475:32: note:   no known conversion for argument 2 from ‘void (QAction::*)(bool)’ to ‘const char*’
/opt/qt5/include/qt5/QtCore/qobject.h:213:43: note: template<class Func1, class Func2> static QMetaObject::Connection QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const typename QtPrivate::FunctionPointer<Func2>::Object*, Func2, Qt::ConnectionType)
     static inline QMetaObject::Connection connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal,
                                           ^
/opt/qt5/include/qt5/QtCore/qobject.h:213:43: note:   template argument deduction/substitution failed:
../../../src/lib/webengine/webview.cpp:858:81: note:   mismatched types ‘const typename QtPrivate::FunctionPointer<Func>::Object*’ and ‘QPointer<QAction>’
             connect(act, &QAction::triggered, this, &WebView::createSearchEngine);
                                                                                 ^
In file included from /opt/qt5/include/qt5/QtCore/qsharedpointer_impl.h:57:0,
                 from /opt/qt5/include/qt5/QtCore/qsharedpointer.h:42,
                 from /opt/qt5/include/qt5/QtGui/qpixmap.h:41,
                 from /opt/qt5/include/qt5/QtGui/qicon.h:40,
                 from /opt/qt5/include/qt5/QtGui/QIcon:1,
                 from ../../../src/lib/webengine/webview.h:21,
                 from ../../../src/lib/webengine/webview.cpp:18:
/opt/qt5/include/qt5/QtCore/qobject.h:245:13: note: template<class Func1, class Func2> static typename QtPrivate::QEnableIf<((int)(QtPrivate::FunctionPointer<Func2>::ArgumentCount) >= 0), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, Func2)
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, Func2 slot)
             ^
/opt/qt5/include/qt5/QtCore/qobject.h:245:13: note:   template argument deduction/substitution failed:
../../../src/lib/webengine/webview.cpp:858:81: note:   mismatched types ‘const typename QtPrivate::FunctionPointer<Func>::Object*’ and ‘QPointer<QAction>’
             connect(act, &QAction::triggered, this, &WebView::createSearchEngine);
                                                                                 ^
In file included from /opt/qt5/include/qt5/QtCore/qsharedpointer_impl.h:57:0,
                 from /opt/qt5/include/qt5/QtCore/qsharedpointer.h:42,
                 from /opt/qt5/include/qt5/QtGui/qpixmap.h:41,
                 from /opt/qt5/include/qt5/QtGui/qicon.h:40,
                 from /opt/qt5/include/qt5/QtGui/QIcon:1,
                 from ../../../src/lib/webengine/webview.h:21,
                 from ../../../src/lib/webengine/webview.cpp:18:
/opt/qt5/include/qt5/QtCore/qobject.h:254:13: note: template<class Func1, class Func2> static typename QtPrivate::QEnableIf<(((int)(QtPrivate::FunctionPointer<Func2>::ArgumentCount) >= 0) && (! QtPrivate::FunctionPointer<Func2>::IsPointerToMemberFunction)), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType)
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, const QObject *context, Func2 slot,
             ^
/opt/qt5/include/qt5/QtCore/qobject.h:254:13: note:   template argument deduction/substitution failed:
../../../src/lib/webengine/webview.cpp:858:81: note:   mismatched types ‘const typename QtPrivate::FunctionPointer<Func>::Object*’ and ‘QPointer<QAction>’
             connect(act, &QAction::triggered, this, &WebView::createSearchEngine);
                                                                                 ^
In file included from /opt/qt5/include/qt5/QtCore/qsharedpointer_impl.h:57:0,
                 from /opt/qt5/include/qt5/QtCore/qsharedpointer.h:42,
                 from /opt/qt5/include/qt5/QtGui/qpixmap.h:41,
                 from /opt/qt5/include/qt5/QtGui/qicon.h:40,
                 from /opt/qt5/include/qt5/QtGui/QIcon:1,
                 from ../../../src/lib/webengine/webview.h:21,
                 from ../../../src/lib/webengine/webview.cpp:18:
/opt/qt5/include/qt5/QtCore/qobject.h:285:13: note: template<class Func1, class Func2> static typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, Func2)
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, Func2 slot)
             ^
/opt/qt5/include/qt5/QtCore/qobject.h:285:13: note:   template argument deduction/substitution failed:
../../../src/lib/webengine/webview.cpp:858:81: note:   mismatched types ‘const typename QtPrivate::FunctionPointer<Func>::Object*’ and ‘QPointer<QAction>’
             connect(act, &QAction::triggered, this, &WebView::createSearchEngine);
                                                                                 ^
In file included from /opt/qt5/include/qt5/QtCore/qsharedpointer_impl.h:57:0,
                 from /opt/qt5/include/qt5/QtCore/qsharedpointer.h:42,
                 from /opt/qt5/include/qt5/QtGui/qpixmap.h:41,
                 from /opt/qt5/include/qt5/QtGui/qicon.h:40,
                 from /opt/qt5/include/qt5/QtGui/QIcon:1,
                 from ../../../src/lib/webengine/webview.h:21,
                 from ../../../src/lib/webengine/webview.cpp:18:
/opt/qt5/include/qt5/QtCore/qobject.h:293:13: note: template<class Func1, class Func2> static typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType)
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, const QObject *context, Func2 slot,
             ^
/opt/qt5/include/qt5/QtCore/qobject.h:293:13: note:   template argument deduction/substitution failed:
../../../src/lib/webengine/webview.cpp:858:81: note:   mismatched types ‘const typename QtPrivate::FunctionPointer<Func>::Object*’ and ‘QPointer<QAction>’
             connect(act, &QAction::triggered, this, &WebView::createSearchEngine);
                                                                                 ^
make[1]: *** [../../../build/webview.o] Erreur 1
```

**Comment by cranes-bill** [comment]
I'm just posting here backtrace of the crash which i have any time on exit.
If this crash is related to the my _webview.cpp_ hack, just ignore it please!

```
#0  0x00007ffff33018a1 in base::ThreadTaskRunnerHandle::Get() ()
   from /opt/qt5/lib64/libQt5WebEngineCore.so.5
#1  0x00007ffff33022b3 in base::internal::PostTaskAndReplyImpl::PostTaskAndReply(tracked_objects::Location const&, base::Callback<void ()> const&, base::Callback<void ()> const&) () from /opt/qt5/lib64/libQt5WebEngineCore.so.5
#2  0x00007ffff330181c in base::TaskRunner::PostTaskAndReply(tracked_objects::Location const&, base::Callback<void ()> const&, base::Callback<void ()> const&)
    () from /opt/qt5/lib64/libQt5WebEngineCore.so.5
#3  0x00007ffff281528f in content::BrowserThread::PostTaskAndReply(content::BrowserThread::ID, tracked_objects::Location const&, base::Callback<void ()> const&, base::Callback<void ()> const&) ()
   from /opt/qt5/lib64/libQt5WebEngineCore.so.5
#4  0x00007ffff282798e in content::DevToolsHttpHandlerImpl::Stop() ()
   from /opt/qt5/lib64/libQt5WebEngineCore.so.5
#5  0x00007ffff0ef3fdc in QtWebEngineCore::DevToolsHttpHandlerDelegateQt::~DevToolsHttpHandlerDelegateQt (this=0x8ec3c0, __in_chrg=<optimized out>)
    at /home/az/rpmbuild/BUILD/qtwebengine-opensource-src-5.5.1/src/core/dev_tools_http_handler_delegate_qt.cpp:182
#6  0x00007ffff0ef4029 in QtWebEngineCore::DevToolsHttpHandlerDelegateQt::~DevToolsHttpHandlerDelegateQt (this=0x8ec3c0, __in_chrg=<optimized out>)
    at /home/az/rpmbuild/BUILD/qtwebengine-opensource-src-5.5.1/src/core/dev_tools_http_handler_delegate_qt.cpp:183
#7  0x00007ffff0f16213 in operator() (this=0x8b9c08, ptr=<optimized out>)
    at /home/az/rpmbuild/BUILD/qtwebengine-opensource-src-5.5.1/src/3rdparty/chromium/base/memory/scoped_ptr.h:127
#8  ~scoped_ptr_impl (this=0x8b9c08, __in_chrg=<optimized out>)
    at /home/az/rpmbuild/BUILD/qtwebengine-opensource-src-5.5.1/src/3rdparty/chromium/base/memory/scoped_ptr.h:221
#9  ~scoped_ptr (this=0x8b9c08, __in_chrg=<optimized out>)
    at /home/az/rpmbuild/BUILD/qtwebengine-opensource-src-5.5.1/src/3rdparty/chromium/base/memory/scoped_ptr.h:311
#10 WebEngineContext::~WebEngineContext (this=0x8b9bd0, 
    __in_chrg=<optimized out>)
    at /home/az/rpmbuild/BUILD/qtwebengine-opensource-src-5.5.1/src/core/web_engine_context.cpp:164
#11 0x00007ffff0f162f1 in Release (this=0x8b9bd0)
    at /home/az/rpmbuild/BUILD/qtwebengine-opensource-src-5.5.1/src/3rdparty/chromium/base/memory/ref_counted.h:137
#12 Release (ptr=0x8b9bd0)
    at /home/az/rpmbuild/BUILD/qtwebengine-opensource-src-5.5.1/src/3rdparty/chromium/base/memory/ref_counted.h:382
#13 operator= (p=0x0, this=0x7ffff49ef810 <(anonymous namespace)::sContext>)
    at /home/az/rpmbuild/BUILD/qtwebengine-opensource-src-5.5.1/src/3rdparty/chromium/base/memory/ref_counted.h:323
#14 (anonymous namespace)::destroyContext ()
    at /home/az/rpmbuild/BUILD/qtwebengine-opensource-src-5.5.1/src/core/web_engine_context.cpp:98
#15 0x00007ffff6ec2231 in qt_call_post_routines ()
    at kernel/qcoreapplication.cpp:293
#16 0x00007ffff7278716 in QApplication::~QApplication (this=0x7fffffffddf0, 
    __in_chrg=<optimized out>) at kernel/qapplication.cpp:821
#17 0x0000000000402afb in main (argc=1, argv=<optimized out>)
    at ../../../src/main/main.cpp:159
```

**Comment by nowrep** [comment]
Your patch should no longer be needed.

**Comment by cranes-bill** [comment]
Yeah thanks!
But the crash still persist...
Do i need to open a new issue about it?

**Comment by nowrep** [comment]
No, unless it happens also with Qt 5.6
