### ISSUE TITLE
crash when trying to save video from youtube

### ISSUE THREAD

**Issue by nekoswag** [QupZilla/qupzilla#2239]
When right clicking on a youtube video and trying to save the file, Qupzilla crashes.

Qupzilla 2.1.1 on openSUSE Tumbleweed

**Comment by nowrep** [comment]
Please post backtrace from `gdb`.

**Comment by nekoswag** [comment]
`Thread 1 "qupzilla" received signal SIGSEGV, Segmentation fault.
0x00007ffff18da2f0 in QUrl::isEmpty() const () from /usr/lib64/libQt5Core.so.5
(gdb) backtrace
#0  0x00007ffff18da2f0 in QUrl::isEmpty() const () from /usr/lib64/libQt5Core.so.5
#1  0x00007ffff18da339 in QUrl::isValid() const () from /usr/lib64/libQt5Core.so.5
#2  0x00007ffff04e715d in QWebEnginePage::triggerAction(QWebEnginePage::WebAction, bool) ()
   from /usr/lib64/libQt5WebEngineWidgets.so.5
#3  0x00007ffff7aa17f9 in ?? () from /usr/lib64/libQupZilla.so.2
#4  0x00007ffff19af709 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib64/libQt5Core.so.5
#5  0x00007ffff1f2a4e2 in QAction::triggered(bool) () from /usr/lib64/libQt5Widgets.so.5
#6  0x00007ffff1f2ced0 in QAction::activate(QAction::ActionEvent) ()
   from /usr/lib64/libQt5Widgets.so.5
#7  0x00007ffff209c4ba in ?? () from /usr/lib64/libQt5Widgets.so.5
#8  0x00007ffff20a3b44 in ?? () from /usr/lib64/libQt5Widgets.so.5
#9  0x00007ffff20a4b16 in QMenu::mouseReleaseEvent(QMouseEvent*) ()
   from /usr/lib64/libQt5Widgets.so.5
#10 0x00007ffff1f78588 in QWidget::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#11 0x00007ffff20a6e43 in QMenu::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#12 0x00007ffff1f30eac in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Widgets.so.5
#13 0x00007ffff1f3951d in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Widgets.so.5
#14 0x00007ffff1983b00 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Core.so.5
#15 0x00007ffff1f37bcd in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib64/libQt5Widgets.so.5
#16 0x00007ffff1f93016 in ?? () from /usr/lib64/libQt5Widgets.so.5
#17 0x00007ffff1f95613 in ?? () from /usr/lib64/libQt5Widgets.so.5
#18 0x00007ffff1f30eac in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Widgets.so.5
#19 0x00007ffff1f38661 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Widgets.so.5
#20 0x00007ffff1983b00 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Core.so.5
#21 0x00007fffef7fac43 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivat---Type <return> to continue, or q <return> to quit---
e::MouseEvent*) () from /usr/lib64/libQt5Gui.so.5
#22 0x00007fffef7fc7c5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib64/libQt5Gui.so.5
#23 0x00007fffef7da75b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Gui.so.5
#24 0x00007fffe1e24210 in ?? () from /usr/lib64/libQt5XcbQpa.so.5
#25 0x00007fffed7b9697 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#26 0x00007fffed7b9900 in ?? () from /usr/lib64/libglib-2.0.so.0
#27 0x00007fffed7b99ac in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#28 0x00007ffff19d816f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#29 0x00007ffff1981aea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#30 0x00007ffff198a25c in QCoreApplication::exec() () from /usr/lib64/libQt5Core.so.5
#31 0x0000000000402e7b in ?? ()
#32 0x00007ffff0de1291 in __libc_start_main () from /lib64/libc.so.6
#33 0x000000000040319a in ?? ()`
