### ISSUE TITLE
Falkon crashes when restoring session

### ISSUE THREAD

**Issue by JuPlutonic** [QupZilla/qupzilla#2511]
[session.dat.zip](https://github.com/QupZilla/qupzilla/files/1521722/session.dat.zip)
Bug in https://github.com/KDE/falkon 4f8b1f5
CMAKE_BUILD_TYPE RelWithDebInfo
qt5.9.3 cmake3.10 backward compatibility 2.4 Linux 4.4.0-102-generic x86_6 Ubuntu 16.04.3 LTS
Something wrong in last 6 restored sites from session.dat. When last remembered 6 sites unchecked falkon restores well.
```
(gdb) run
Starting program: /opt/bin/falkon 
warning: File "/opt/.linuxbrew/Cellar/gcc/5.4.0/lib/libstdc++.so.6.0.21-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /opt/.linuxbrew/Cellar/gcc/5.4.0/lib/libstdc++.so.6.0.21-gdb.py
line to your configuration file "/home/salessionato/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/salessionato/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe1ddb700 (LWP 22334)]
QApplication: invalid style override passed, ignoring it.
[New Thread 0x7fffd2f97700 (LWP 22344)]
[New Thread 0x7fffd2796700 (LWP 22352)]
[New Thread 0x7fffd1f95700 (LWP 22353)]
[New Thread 0x7fffd1794700 (LWP 22354)]
[New Thread 0x7fffd0f93700 (LWP 22355)]
[New Thread 0x7fffbbfff700 (LWP 22356)]
[New Thread 0x7fffbb7fe700 (LWP 22357)]
[New Thread 0x7fffbaffd700 (LWP 22358)]
[New Thread 0x7fffba7fc700 (LWP 22359)]
[New Thread 0x7fffb9ffb700 (LWP 22360)]
[New Thread 0x7fffb97fa700 (LWP 22361)]
[New Thread 0x7fffb8ff9700 (LWP 22362)]
[New Thread 0x7fff9b7fe700 (LWP 22364)]
[New Thread 0x7fff9bfff700 (LWP 22363)]
[New Thread 0x7fff9affd700 (LWP 22365)]
[New Thread 0x7fff9a7fc700 (LWP 22366)]
[New Thread 0x7fff99ffb700 (LWP 22367)]
[New Thread 0x7fff997fa700 (LWP 22368)]
[New Thread 0x7fff98911700 (LWP 22369)]
[New Thread 0x7fff73ddf700 (LWP 22373)]
[New Thread 0x7fff735de700 (LWP 22374)]
Falkon: 6 extensions loaded
[New Thread 0x7fff7122b700 (LWP 22381)]
[New Thread 0x7fff6388a700 (LWP 22402)]
[Thread 0x7fff6388a700 (LWP 22402) exited]

Thread 1 "falkon" received signal SIGSEGV, Segmentation fault.
0x00007ffff18d4b51 in ?? () from /opt/qt59/lib/libQt5WebEngineCore.so.5
(gdb) backtrace
#0  0x00007ffff18d4b51 in ?? () from /opt/qt59/lib/libQt5WebEngineCore.so.5
#1  0x00007ffff7e76092 in QMetaObjectPublisher::handleMessage(QJsonObject const&, QWebChannelAbstractTransport*) () from /opt/qt59/lib/libQt5WebChannel.so.5
#2  0x00007fffef2561a6 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /opt/qt59/lib/libQt5Core.so.5
#3  0x00007ffff7e7ba34 in QWebChannelAbstractTransport::messageReceived(QJsonObject const&, QWebChannelAbstractTransport*) () from /opt/qt59/lib/libQt5WebChannel.so.5
#4  0x00007ffff18d4af3 in ?? () from /opt/qt59/lib/libQt5WebEngineCore.so.5
#5  0x00007ffff18d4d5b in ?? () from /opt/qt59/lib/libQt5WebEngineCore.so.5
#6  0x00007ffff1e0fe9b in ?? () from /opt/qt59/lib/libQt5WebEngineCore.so.5
#7  0x00007ffff1d3e500 in ?? () from /opt/qt59/lib/libQt5WebEngineCore.so.5
#8  0x00007ffff1d4d126 in ?? () from /opt/qt59/lib/libQt5WebEngineCore.so.5
#9  0x00007ffff1d37743 in ?? () from /opt/qt59/lib/libQt5WebEngineCore.so.5
#10 0x00007ffff2a2fe56 in ?? () from /opt/qt59/lib/libQt5WebEngineCore.so.5
#11 0x00007ffff21ffbc9 in ?? () from /opt/qt59/lib/libQt5WebEngineCore.so.5
#12 0x00007ffff21a4f60 in ?? () from /opt/qt59/lib/libQt5WebEngineCore.so.5
#13 0x00007ffff21a6c2d in ?? () from /opt/qt59/lib/libQt5WebEngineCore.so.5
#14 0x00007ffff21a70e8 in ?? () from /opt/qt59/lib/libQt5WebEngineCore.so.5
#15 0x00007ffff1898805 in ?? () from /opt/qt59/lib/libQt5WebEngineCore.so.5
#16 0x00007fffef256e73 in QObject::event(QEvent*) () from /opt/qt59/lib/libQt5Core.so.5
#17 0x00007ffff0c7b55c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /opt/qt59/lib/libQt5Widgets.so.5
#18 0x00007ffff0c82f67 in QApplication::notify(QObject*, QEvent*) ()
   from /opt/qt59/lib/libQt5Widgets.so.5
#19 0x00007fffef2299f8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /opt/qt59/lib/libQt5Core.so.5
#20 0x00007fffef22c1db in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /opt/qt59/lib/libQt5Core.so.5
#21 0x00007fffef27fca3 in ?? () from /opt/qt59/lib/libQt5Core.so.5
#22 0x00007fffeda454e7 in g_main_dispatch (context=0x7fffdc0016f0) at gmain.c:3148
#23 g_main_context_dispatch (context=context@entry=0x7fffdc0016f0) at gmain.c:3813
#24 0x00007fffeda45728 in g_main_context_iterate (context=context@entry=0x7fffdc0016f0, 
    block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3886
#25 0x00007fffeda457cc in g_main_context_iteration (context=0x7fffdc0016f0, may_block=1)
    at gmain.c:3947
#26 0x00007fffef27f2af in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/qt59/lib/libQt5Core.so.5
#27 0x00007fffef227a2a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /opt/qt59/lib/libQt5Core.so.5
#28 0x00007fffef230964 in QCoreApplication::exec() () from /opt/qt59/lib/libQt5Core.so.5
#29 0x00000000004038ec in main ()
```

**Comment by JuPlutonic** [comment]
If it is QTWebEngine bug I can apply to qt's bugreports

**Comment by nowrep** [comment]
Yes, the backtrace is entirely in Qt (QtWebEngine/QtWebChannel)).
